### ISSUE TITLE
Crash in condition handler

### ISSUE THREAD

**Issue by renzenicolai** [athombv/com.athom.homeyduino#44]
A crash occurred for your app (version 1.0.1) at Jan 17, 2018 1:24 PM (UTC).

Homey software version: 1.5.6-rc.8

Crash report:

    
Note: this log has been manually submitted by a user.
Log ID: 7ce8eb8d-ae27-4782-be37-9b4b471c0376

---- stdout ----

---- stderr ----
/app.js:174
		return args.device.condition(args);
		                   ^

TypeError: args.device.condition is not a function
    at HomeyduinoApp.onCondition (/app.js:174:22)
    at FlowCardCondition._onRun (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCard.js:1:1191)
    at emitThree (events.js:136:13)
    at FlowCardCondition.emit (events.js:217:7)
    at ManagerFlow._onRun (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/flow.js:1:2274)
    at _eventListeners.filter.forEach.t (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1219)
    at Array.forEach (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1196)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)

**Comment by renzenicolai** [comment]
hopefully this doesn't happen in the release version...
